steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lokey-backend:$COMMIT_SHA', '.']

  # Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lokey-backend:$COMMIT_SHA']

  # Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'lokey-backend'
    - '--image=gcr.io/$PROJECT_ID/lokey-backend:$COMMIT_SHA'
    - '--region=asia-northeast3'  # 서울 리전
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--memory=512Mi'
    - '--cpu=1'
    - '--timeout=300'
    - '--concurrency=1000'
    - '--max-instances=10'

images:
  - 'gcr.io/$PROJECT_ID/lokey-backend:$COMMIT_SHA'